version: "3.9"
services:
  bytebin:
    image: orewaee/bytebin:latest
    container_name: bytebin
    restart: unless-stopped
    command: "--config=../config/example.yaml"
    volumes:
      - ../config/example.yaml:/config/example.yaml
    ports:
      - "8081:8080"
    networks:
      - bytebin
networks:
  bytebin:
    driver: bridge
volumes:
  bytebin:
